### ISSUE TITLE
MCP server aborts when attempting to summarize URLs that Kagi web summarizer fails on

### ISSUE THREAD

**Issue by Dual-0** [kagisearch/kagimcp#8]
**Description:**

When using the `kagimcp` server to summarize a URL that the [Kagi web summarizer](https://kagi.com/summarizer/index.html) is unable to extract content from, the MCP server process appears to abort instead of handling the error gracefully.

This behaviour was observed when using `kagimcp` integrated with LibreChat, but the issue seems to be within the `kagimcp` server itself.

**Steps to Reproduce:**

1.  Set up `kagimcp` and integrate it with a client like LibreChat or use the MCP inspector.
2.  Attempt to summarize a URL that is known to fail on the Kagi web summarizer.
3.  Observe the `kagimcp` server logs and the client logs.

**Expected Behavior:**

The `kagimcp` server should handle the inability to summarize a source gracefully. It should return an appropriate error message to the client (e.g., indicating that the source could not be extracted) and continue running, rather than aborting the process.

**Observed Behavior:**

The `kagimcp` process appears to abort or encounter a fatal error, leading to a "This operation was aborted" error in the client application (LibreChat in this case).

**Relevant Information:**

*   **Example Failing URL:** https://www.wsj.com/articles/nvidia-thinks-it-has-a-better-way-of-building-ai-agents-b289a574
*   **LibreChat Logs:**
    ```
    2025-04-28 10:06:56 info: [MCP][User: 65ef2e29683dc71c33b9b084][kagi] Establishing new connection
    realpath: --: No such file or directory
    2025-04-28 10:06:57 info: [MCP][User: 65ef2e29683dc71c33b9b084][kagi] Connection successfully established
    [04/28/25 10:06:57] INFO     Processing request of type            server.py:534
                                 CallToolRequest
    2025-04-28 10:07:57 error: [MCP][User: 65ef2e29683dc71c33b9b084][kagi][kagi_summarizer] Tool call failed This operation was aborted
    2025-04-28 10:07:57 error: [MCP][User: 65ef2e29683dc71c33b9b084][kagi] Error calling "kagi_summarizer" MCP tool: This operation was aborted
    2025-04-28 10:07:57 error: [api/server/controllers/agents/client.js #chatCompletion] Tool Error "kagi_summarizer_mcp_kagi" tool call failed: This operation was aborted
    2025-04-28 10:07:57 error: [api/server/controllers/agents/client.js #sendCompletion] Operation aborted Aborted
    ```
*   **LibreChat MCP Config Part:**
    ```yaml
    mcpServers:
      kagi:
        type: stdio
        command: uvx
        args:
          - kagimcp
        env:
          KAGI_API_KEY: "YOUR_API_KEY_HERE" # Key redacted
          KAGI_SUMMARIZER_ENGINE: "agnes"
          FASTMCP_LOG_LEVEL: "INFO"
          PATH: /bin:/usr/bin
    ```
*   **Kagi Web Summarizer Message for same URL:** "Wir entschuldigen uns dafür, die Quelle nicht extrahieren zu können." (We apologize for not being able to extract the source.)

This issue suggests that the `kagimcp` server might not be correctly handling the specific error response from the Kagi Summarizer API when a source cannot be extracted, leading to an unhandled exception or similar issue that causes the process to terminate or abort the current operation.

Thank you for looking into this.

**Comment by rehanzo** [comment]
Thank you for the report, and for the very detailed information.

I don't use librechat, but I could replicate in the MCP inspector. What is happening in the MCP inspector is that the request takes a while, and so it times out. Under configuration, the timeout in the inspector can be increased. 

Looking it up, the same can be done in librechat. Looking at the [docs](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/mcp_servers), the timeout might be set like so:

```
mcpServers:
  kagi:
    type: stdio
    command: uvx
    args:
      - kagimcp
    timeout: 120000
    env:
      KAGI_API_KEY: "YOUR_API_KEY_HERE" # Key redacted
      KAGI_SUMMARIZER_ENGINE: "agnes"
      FASTMCP_LOG_LEVEL: "INFO"
      PATH: /bin:/usr/bin
```

So give that a go and let me know.
